
GET http://localhost:8080/asset-types
Content-Type: application/json


###

POST http://localhost:8080/asset-types/
Content-Type: application/json

{
  "name": {
    "de-DE": "Test Typ 2"
  },
  "equipmentType": "ENTERPRISE",
  "extendsType": null
}

###

GET http://localhost:8080/asset-types/57004405-948a-4b78-b4fe-16d5325bd2b6
Content-Type: application/json

###

PATCH http://localhost:8080/asset-types/57004405-948a-4b78-b4fe-16d5325bd2b6
Content-Type: application/json

{
  "name": {
    "de-DE": "Ein neuer Name - Tadao"
  },
  "equipmentType": "NONE"
}
